### PR TITLE
Recursively sort nested resources

### LINKED ISSUE #30: Sort API definition JSON before generating typings
Discovery API returns methods not in the same order, so I had to use [deep-sort-object](https://www.npmjs.com/package/deep-sort-object) before comparing old and new API version. I think we should also use it (or some similar) approach for typings generation as well, so that we won't get tons of false-changes.

_Originally posted by @Maxim-Mazurok in https://github.com/Maxim-Mazurok/google-api-typings-generator/issues/15#issuecomment-571508608_

### PR DESCRIPTION
**Pull request by namoscato**
Fixes #30

## Details

* Move mocha configuration to `.mocharc.json`
* Replace custom `forEachOrdered` and `sortKeys` methods with `deep-sort-object`

## Testing

Ensure something like this outputs the same result on consecutive runs:

```
$ npx ts-node -T src/cli.ts --out ./types --url https://accessapproval.googleapis.com/\$discovery/rest?version=v1 && md5 types/gapi.client.accessapproval/index.d.ts
```

### CODE REVIEW

**Comment by Maxim-Mazurok** [comment]
I'll review it in detail tomorrow, but quick comment:
In #25 I'm just sorting the whole JSON, using `deep-sort-object` npm package (maybe not the best one, but it works)
So, why don't we use the same approach? Maybe just pick the best deep object sorter out there, maybe something from lodash.
What do you think?

**Comment by namoscato** [comment]
> So, why don't we use the same approach here?

Yeah, I would be cool using `deep-sort-object` so we don't have to own that logic.

I also realized that we might be able to get rid of a custom `forEachOrdered` method as well.

**Comment by Maxim-Mazurok** [comment]
> I don't think I see any harm in doing so (i.e. I doubt it will add noticeable time to the build).

Yeah, I think sorting time complexity is nothing when compared to HTTP requests that we make to get API definitions :) 

> I also realized that we might be able to get rid of a custom `forEachOrdered` method as well.

Yes, nice catch!

**Comment by namoscato** [comment]
@Maxim-Mazurok, this should be good to go now, and I had done some more manual testing as described above. I would like to try and wrap up some of these smaller items before running prettier in https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/41 (which will likely cause some conflicts).

**Pull request merged**
