### PR TITLE
Remove editor settings files

### PR DESCRIPTION
**Pull request by namoscato**
The committed `.idea` folder is specifically causing issues for me as it includes some user-specific stuff that should be ignored. I ignore `.idea` [globally](https://help.github.com/en/github/using-git/ignoring-files#create-a-global-gitignore), but we could add it to this project's local gitignore if you would like or incorporate [JetBrains.gitignore](https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore).

### CODE REVIEW

**Comment by Maxim-Mazurok** [comment]
Yes, I usually try to exclude user-specific files. I thought that IDEA already takes care about it automatically. Seems like it's not handling all files. Let's use JetBrains.gitignore instead of removing the whole directory, I think it makes sense since we both seem to use IDEA.

**Comment by namoscato** [comment]
Sounds good, should we remove `.vscode/` as well?

**Comment by Maxim-Mazurok** [comment]
Yes, I believe it is left from the original repo. In case if any future contributors will use VC code, they could add their preferred config. So we can remove `.vscode/` completely for now.

**Comment by namoscato** [comment]
I think the missing `google-api-typings-generator.iml` file was actually causing the issue for me, but I went ahead and removed the (few) files ignored by [JetBrains.gitignore](https://github.com/github/gitignore/blob/master/Global/JetBrains.gitignore) as well (specifically https://github.com/namoscato/dotfiles/commit/a2512a2bb3e86d2e788c7426a31d807cbe3f3371).

The end result basically:

* Removes user-specific dictionary
* Adds `.idea/google-api-typings-generator.iml`
* Marks `src`, `tests`, and `types` directories appropriately

Let me know if this works for you!

**Comment by Maxim-Mazurok** [comment]
I see, `*.iml` file was in root folder for me.
But your changes work for me, let's go ahead with it. I'll open PR with JetBrains.gitignore.
Could you create branches inside this repo and not the fork in the future, please? So that I could push my commits to your PRs, such as adding JetBrains.gitignore.
Thanks for cleaning up the mess :)

**Pull request merged**
