### PR TITLE
Remove unused App.parseVersion

### PR DESCRIPTION
**Pull request by namoscato**
## Details

Removes unused `App.parseVersion` method, and moves test coverage to renamed `convertVersion`

## Dependencies

* https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/39

### CODE REVIEW

**Comment by namoscato** [comment]
It's still expected for [`test`](https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/42/checks?check_run_id=429535374) to be failing as we haven't run prettier yet, but it looks like [`lint`](https://github.com/Maxim-Mazurok/google-api-typings-generator/pull/42/checks?check_run_id=429535346) is also failing for at least `adexchangebuyer` 🤔

**Comment by Maxim-Mazurok** [comment]
Right, it seems like this endpoint also started returning response gzipped.
I have fixed this issue here: https://github.com/Maxim-Mazurok/google-api-typings-generator/commit/bac7899fd930e7e52d17c97e78a9cf9992677799

Also, I was investigating why we have to run ts-node with `-T` flag. I haven't found a solution to fix that yet. But we can also use the same approach to run mocha with `ts-node/register`, we just have to ask it to run in transpile-only mode. You can ignore this for now, I'll update it later when I solve this.

**Comment by namoscato** [comment]
> Right, it seems like this endpoint also started returning response gzipped.
> I have fixed this issue here: [bac7899](https://github.com/Maxim-Mazurok/google-api-typings-generator/commit/bac7899fd930e7e52d17c97e78a9cf9992677799)

Weird – good find.

Sounds good. Should we merge this one as-is then?

**Comment by Maxim-Mazurok** [comment]
No, please, copy this change: https://github.com/Maxim-Mazurok/google-api-typings-generator/commit/bac7899fd930e7e52d17c97e78a9cf9992677799

Because it's only in my diff generation branch currently, that will never be merged. Thanks!

**Comment by namoscato** [comment]
@Maxim-Mazurok, there is still an issue with at least some of the generated tests, i.e.

```
$ npm run dtslint types/gapi.client.adexchangebuyer

> google-api-typings-generator@ dtslint /Users/namoscato/dev/git/google-api-typings-generator
> dtslint "types/gapi.client.adexchangebuyer"

Error: /Users/namoscato/dev/git/google-api-typings-generator/types/gapi.client.adexchangebuyer/gapi.client.adexchangebuyer-tests.ts:35:52
ERROR: 35:52    expect  TypeScript@next compile error: 
Expected 1 arguments, but got 0.
ERROR: 83:55    expect  TypeScript@next compile error: 
Expected 1 arguments, but got 0.
ERROR: 128:60   expect  TypeScript@next compile error: 
Argument expression expected.
ERROR: 129:13   expect  TypeScript@next compile error: 
Argument of type '{ accountId: number; adChoicesDestinationUrl: string; adTechnologyProviders: { detectedProviderIds: string[]; hasUnidentifiedProvider: boolean; }; advertiserId: string[]; advertiserName: string; ... 25 more ...; width: number; }' is not assignable to parameter of type '{ alt?: string | undefined; fields?: string | undefined; key?: string | undefined; oauth_token?: string | undefined; prettyPrint?: boolean | undefined; quotaUser?: string | undefined; userIp?: string | undefined; resource: Creative; }'.
  Object literal may only specify known properties, and 'accountId' does not exist in type '{ alt?: string | undefined; fields?: string | undefined; key?: string | undefined; oauth_token?: string | undefined; prettyPrint?: boolean | undefined; quotaUser?: string | undefined; userIp?: string | undefined; resource: Creative; }'.
ERROR: 1082:60  expect  TypeScript@next compile error: 
Argument expression expected.
ERROR: 1083:13  expect  TypeScript@next compile error: 
Argument of type '{ proposals: { billedBuyer: { accountId: string; }; buyer: { accountId: string; }; buyerContacts: { email: string; name: string; }[]; buyerPrivateData: { referenceId: string; referencePayload: string; }; ... 18 more ...; sellerContacts: { ...; }[]; }[]; webPropertyCode: string; }' is not assignable to parameter of type '{ alt?: string | undefined; fields?: string | undefined; key?: string | undefined; oauth_token?: string | undefined; prettyPrint?: boolean | undefined; quotaUser?: string | undefined; userIp?: string | undefined; resource: CreateOrdersRequest; }'.
  Object literal may only specify known properties, and 'proposals' does not exist in type '{ alt?: string | undefined; fields?: string | undefined; key?: string | undefined; oauth_token?: string | undefined; prettyPrint?: boolean | undefined; quotaUser?: string | undefined; userIp?: string | undefined; resource: CreateOrdersRequest; }'.

    at /Users/namoscato/dev/git/google-api-typings-generator/node_modules/dtslint/bin/index.js:193:19
```

I'm looking into it, but let me know if you have any thoughts?

I doubt it's related to these changes.

**Comment by Maxim-Mazurok** [comment]
Yeah, I don't think that these changes affect tests
Hence, merging. Thank you!

**Pull request merged**
